import { CategoryWiseProduct } from "@/lip/types/product";

const CategoriesWiseProduct: CategoryWiseProduct[] = [
  {
    category: "স্কিনকেয়ার",
    slug: "skincare",
    banner:
      "https://t3.ftcdn.net/jpg/02/28/47/78/360_F_228477803_rvOdKapC3wLKWl8tYaYmvQOLXcxFYD3G.jpg",
    products: [
      {
        id: "1",
        name: "গ্লো রেডিয়েন্স ভিটামিন সি সেরাম",
        slug: "glow-radiance-vitamin-c-serum",
        description:
          "উন্নত ভিটামিন সি ফর্মুলা যা ত্বককে উজ্জ্বল করে এবং বয়সের ছাপ কমায়। প্রাকৃতিক উপাদান দিয়ে তৈরি।",
        shortDescription: "ভিটামিন সি সেরাম - ত্বকের উজ্জ্বলতার জন্য",
        sku: "GRC-001",
        price: 1200,
        salePrice: 950,
        images: [
          "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "sk-1",
          name: "স্কিনকেয়ার",
          slug: "skincare",
          description: "ত্বকের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 1,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-15").toISOString(),
        },
        categoryId: "sk-1",
        tags: ["serum", "vitamin-c", "anti-aging", "brightening"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "GlowCare",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.8,
        reviewsCount: 124,
        hasVariants: false,
        salesCount: 89,
        viewsCount: 2156,
        wishlistCount: 45,
        createdAt: new Date("2024-01-01").toISOString(),
        updatedAt: new Date("2024-01-15").toISOString(),
      },
      {
        id: "2",
        name: "হাইড্রেটিং ফেসিয়াল ক্রিম",
        slug: "hydrating-facial-cream",
        description:
          "দীর্ঘস্থায়ী হাইড্রেশন প্রদানকারী ফেসিয়াল ক্রিম, শুষ্ক ত্বকের জন্য আদর্শ।",
        shortDescription: "ত্বকের হাইড্রেশনের জন্য ফেসিয়াল ক্রিম",
        sku: "HFC-002",
        price: 800,
        salePrice: 700,
        images: [
          "https://images.unsplash.com/photo-1600577916048-804c60c803c1?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600577916048-804c60c803c1?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "sk-1",
          name: "স্কিনকেয়ার",
          slug: "skincare",
          description: "ত্বকের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 1,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-15").toISOString(),
        },
        categoryId: "sk-1",
        tags: ["cream", "hydrating", "moisturizer", "daily-care"],
        stock: 30,
        lowStockThreshold: 5,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "PurelyNatural",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 85,
        hasVariants: true,
        salesCount: 60,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-02-01").toISOString(),
        updatedAt: new Date("2024-02-10").toISOString(),
      },
    ],
  },
  {
    category: "হেয়ার কেয়ার",
    slug: "haircare",
    banner:
      "https://cdn.vectorstock.com/i/500p/36/73/luxury-cosmetic-banner-vector-23863673.jpg",
    products: [
      {
        id: "3",
        name: "হেয়ার গ্রোথ শ্যাম্পু",
        slug: "hair-growth-shampoo",
        description:
          "চুলের বৃদ্ধি এবং শক্তি বাড়ায় এমন প্রাকৃতিক উপাদান সমৃদ্ধ শ্যাম্পু।",
        shortDescription: "চুলের বৃদ্ধির জন্য শ্যাম্পু",
        sku: "HGS-001",
        price: 600,
        salePrice: 550,
        images: [
          "https://cdn.vectorstock.com/i/500p/36/73/luxury-cosmetic-banner-vector-23863673.jpg",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "hc-1",
          name: "হেয়ার কেয়ার",
          slug: "haircare",
          description: "চুলের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 2,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "hc-1",
        tags: ["shampoo", "hair-growth", "natural", "haircare"],
        stock: 60,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "HairVital",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 80,
        hasVariants: false,
        salesCount: 70,
        viewsCount: 1900,
        wishlistCount: 35,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "4",
        name: "হেয়ার কন্ডিশনার",
        slug: "hair-conditioner",
        description: "চুলকে নরম ও মসৃণ করার জন্য হাইড্রেটিং কন্ডিশনার।",
        shortDescription: "নরম চুলের জন্য কন্ডিশনার",
        sku: "HCD-002",
        price: 500,
        salePrice: 450,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "hc-1",
          name: "হেয়ার কেয়ার",
          slug: "haircare",
          description: "চুলের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 2,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "hc-1",
        tags: ["conditioner", "hydrating", "haircare", "natural"],
        stock: 45,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "HairVital",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.4,
        reviewsCount: 60,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1600,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "মেকআপ",
    slug: "makeup",
    banner:
      "https://images.unsplash.com/photo-1522335786673-5a4a8b3b3e7c?q=80&w=1000&auto=format&fit=crop",
    products: [
      {
        id: "5",
        name: "লিকুইড ফাউন্ডেশন",
        slug: "liquid-foundation",
        description:
          "হালকা ও দীর্ঘস্থায়ী ফাউন্ডেশন, সব ধরনের ত্বকের জন্য উপযুক্ত।",
        shortDescription: "দীর্ঘস্থায়ী লিকুইড ফাউন্ডেশন",
        sku: "LFD-001",
        price: 900,
        salePrice: 800,
        images: [
          "https://images.unsplash.com/photo-1522335786673-5a4a8b3b3e7c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1522335786673-5a4a8b3b3e7c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "mk-1",
          name: "মেকআপ",
          slug: "makeup",
          description: "মেকআপ পণ্য",
          level: 1,
          isActive: true,
          sort: 3,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "mk-1",
        tags: ["foundation", "makeup", "long-lasting", "beauty"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "BeautyGlow",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.6,
        reviewsCount: 95,
        hasVariants: true,
        salesCount: 70,
        viewsCount: 2000,
        wishlistCount: 30,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "6",
        name: "লিপস্টিক",
        slug: "lipstick",
        description: "ম্যাট ফিনিশ লিপস্টিক, বিভিন্ন শেডে পাওয়া যায়।",
        shortDescription: "ম্যাট লিপস্টিক বিভিন্ন শেডে",
        sku: "LPS-002",
        price: 500,
        salePrice: 450,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "mk-1",
          name: "মেকআপ",
          slug: "makeup",
          description: "মেকআপ পণ্য",
          level: 1,
          isActive: true,
          sort: 3,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "mk-1",
        tags: ["lipstick", "matte", "makeup", "beauty"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "BeautyGlow",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.7,
        reviewsCount: 110,
        hasVariants: true,
        salesCount: 90,
        viewsCount: 2500,
        wishlistCount: 40,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "ফ্র্যাগ্রান্স",
    slug: "fragrance",
    banner:
      "https://images.unsplash.com/photo-1587017530108-5a9b0538e1b0?q=80&w=1000&auto=format&fit=crop",
    products: [
      {
        id: "7",
        name: "মহিলাদের পারফিউম",
        slug: "womens-perfume",
        description:
          "দীর্ঘস্থায়ী ফ্লোরাল সুগন্ধি, দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
        shortDescription: "মহিলাদের জন্য ফ্লোরাল পারফিউম",
        sku: "WPF-001",
        price: 2000,
        salePrice: 1800,
        images: [
          "https://images.unsplash.com/photo-1587017530108-5a9b0538e1b0?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1587017530108-5a9b0538e1b0?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "fr-1",
          name: "ফ্র্যাগ্রান্স",
          slug: "fragrance",
          description: "পুরুষ ও মহিলাদের জন্য সুগন্ধি",
          level: 1,
          isActive: true,
          sort: 4,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "fr-1",
        tags: ["perfume", "floral", "womens", "fragrance"],
        stock: 35,
        lowStockThreshold: 7,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "ScentSational",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.8,
        reviewsCount: 85,
        hasVariants: false,
        salesCount: 60,
        viewsCount: 1800,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "8",
        name: "পুরুষদের কোলোন",
        slug: "mens-cologne",
        description: "প্রিমিয়াম কোলোন, পুরুষদের জন্য সতেজ ও মার্জিত সুগন্ধি।",
        shortDescription: "পুরুষদের জন্য সতেজ কোলোন",
        sku: "MCL-002",
        price: 2200,
        salePrice: 2000,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "fr-1",
          name: "ফ্র্যাগ্রান্স",
          slug: "fragrance",
          description: "পুরুষ ও মহিলাদের জন্য সুগন্ধি",
          level: 1,
          isActive: true,
          sort: 4,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "fr-1",
        tags: ["cologne", "mens", "fragrance", "premium"],
        stock: 30,
        lowStockThreshold: 6,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "ScentSational",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.7,
        reviewsCount: 70,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1700,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "নেল কেয়ার",
    slug: "nailcare",
    products: [
      {
        id: "9",
        name: "নেল পলিশ",
        slug: "nail-polish",
        description: "দীর্ঘস্থায়ী নেল পলিশ, বিভিন্ন রঙে পাওয়া যায়।",
        shortDescription: "দীর্ঘস্থায়ী নেল পলিশ",
        sku: "NPL-001",
        price: 300,
        salePrice: 250,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "nc-1",
          name: "নেল কেয়ার",
          slug: "nailcare",
          description: "নখের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 5,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "nc-1",
        tags: ["nail-polish", "beauty", "nailcare", "colorful"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "NailTrend",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 60,
        hasVariants: true,
        salesCount: 50,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "10",
        name: "নেল স্ট্রেংথেনার",
        slug: "nail-strengthener",
        description: "নখকে শক্তিশালী ও স্বাস্থ্যকর করার জন্য নেল স্ট্রেংথেনার।",
        shortDescription: "নখের জন্য স্ট্রেংথেনার",
        sku: "NST-002",
        price: 400,
        salePrice: 350,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "nc-1",
          name: "নেল কেয়ার",
          slug: "nailcare",
          description: "নখের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 5,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "nc-1",
        tags: ["nail-strengthener", "beauty", "nailcare", "healthy"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "NailTrend",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.4,
        reviewsCount: 50,
        hasVariants: false,
        salesCount: 40,
        viewsCount: 1400,
        wishlistCount: 15,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "বডি কেয়ার",
    slug: "bodycare",
    banner:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
    products: [
      {
        id: "11",
        name: "বডি লোশন",
        slug: "body-lotion",
        description:
          "ত্বককে নরম ও হাইড্রেটেড রাখার জন্য প্রাকৃতিক উপাদান সমৃদ্ধ বডি লোশন।",
        shortDescription: "ত্বকের জন্য হাইড্রেটিং বডি লোশন",
        sku: "BLT-001",
        price: 700,
        salePrice: 600,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "bc-1",
          name: "বডি কেয়ার",
          slug: "bodycare",
          description: "শরীরের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 6,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "bc-1",
        tags: ["body-lotion", "hydrating", "bodycare", "natural"],
        stock: 45,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "BodyBliss",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.6,
        reviewsCount: 70,
        hasVariants: false,
        salesCount: 55,
        viewsCount: 1600,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "12",
        name: "বডি স্ক্রাব",
        slug: "body-scrub",
        description: "ত্বকের মৃত কোষ অপসারণের জন্য প্রাকৃতিক বডি স্ক্রাব।",
        shortDescription: "ত্বকের জন্য বডি স্ক্রাব",
        sku: "BSC-002",
        price: 800,
        salePrice: 700,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "bc-1",
          name: "বডি কেয়ার",
          slug: "bodycare",
          description: "শরীরের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 6,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "bc-1",
        tags: ["body-scrub", "exfoliating", "bodycare", "natural"],
        stock: 35,
        lowStockThreshold: 7,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "BodyBliss",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 60,
        hasVariants: false,
        salesCount: 45,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "ফেসিয়াল ক্লিনজার",
    slug: "facial-cleanser",
    products: [
      {
        id: "13",
        name: "ফোমিং ফেস ওয়াশ",
        slug: "foaming-face-wash",
        description:
          "তৈলাক্ত ত্বকের জন্য ফোমিং ফেস ওয়াশ, ত্বককে পরিষ্কার ও সতেজ রাখে।",
        shortDescription: "তৈলাক্ত ত্বকের জন্য ফেস ওয়াশ",
        sku: "FFW-001",
        price: 500,
        salePrice: 450,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "fc-1",
          name: "ফেসিয়াল ক্লিনজার",
          slug: "facial-cleanser",
          description: "ত্বক পরিষ্কারের পণ্য",
          level: 1,
          isActive: true,
          sort: 7,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "fc-1",
        tags: ["face-wash", "cleanser", "oily-skin", "skincare"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "CleanSkin",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.6,
        reviewsCount: 80,
        hasVariants: false,
        salesCount: 60,
        viewsCount: 1700,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "14",
        name: "মাইসেলার ওয়াটার",
        slug: "micellar-water",
        description:
          "মেকআপ অপসারণের জন্য মৃদু মাইসেলার ওয়াটার, সব ধরনের ত্বকের জন্য।",
        shortDescription: "মেকআপ অপসারণের জন্য মাইসেলার ওয়াটার",
        sku: "MWT-002",
        price: 600,
        salePrice: 550,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "fc-1",
          name: "ফেসিয়াল ক্লিনজার",
          slug: "facial-cleanser",
          description: "ত্বক পরিষ্কারের পণ্য",
          level: 1,
          isActive: true,
          sort: 7,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "fc-1",
        tags: ["micellar-water", "cleanser", "makeup-remover", "skincare"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "CleanSkin",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 65,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1600,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "সানস্ক্রিন",
    slug: "sunscreen",
    products: [
      {
        id: "15",
        name: "এসপিএফ ৫০ সানস্ক্রিন",
        slug: "spf-50-sunscreen",
        description:
          "উচ্চ সুরক্ষা প্রদানকারী এসপিএফ ৫০ সানস্ক্রিন, ত্বককে সূর্যের ক্ষতি থেকে রক্ষা করে।",
        shortDescription: "এসপিএফ ৫০ সানস্ক্রিন ত্বকের সুরক্ষার জন্য",
        sku: "SPF-001",
        price: 800,
        salePrice: 700,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "ss-1",
          name: "সানস্ক্রিন",
          slug: "sunscreen",
          description: "সূর্যের ক্ষতি থেকে ত্বকের সুরক্ষা",
          level: 1,
          isActive: true,
          sort: 8,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "ss-1",
        tags: ["sunscreen", "spf-50", "sun-protection", "skincare"],
        stock: 45,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "SunSafe",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.7,
        reviewsCount: 75,
        hasVariants: false,
        salesCount: 60,
        viewsCount: 1800,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "16",
        name: "লাইটওয়েট সানস্ক্রিন",
        slug: "lightweight-sunscreen",
        description:
          "হালকা ও নন-গ্রিজি সানস্ক্রিন, দৈনন্দিন ব্যবহারের জন্য আদর্শ।",
        shortDescription: "হালকা সানস্ক্রিন দৈনন্দিন ব্যবহারের জন্য",
        sku: "LWS-002",
        price: 600,
        salePrice: 550,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "ss-1",
          name: "সানস্ক্রিন",
          slug: "sunscreen",
          description: "সূর্যের ক্ষতি থেকে ত্বকের সুরক্ষা",
          level: 1,
          isActive: true,
          sort: 8,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "ss-1",
        tags: ["sunscreen", "lightweight", "sun-protection", "skincare"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "SunSafe",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 60,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "লিপ কেয়ার",
    slug: "lipcare",
    products: [
      {
        id: "17",
        name: "লিপ বাম",
        slug: "lip-balm",
        description:
          "শুষ্ক ঠোঁটের জন্য হাইড্রেটিং লিপ বাম, প্রাকৃতিক উপাদান দিয়ে তৈরি।",
        shortDescription: "হাইড্রেটিং লিপ বাম",
        sku: "LPB-001",
        price: 300,
        salePrice: 250,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "lc-1",
          name: "লিপ কেয়ার",
          slug: "lipcare",
          description: "ঠোঁটের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 9,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "lc-1",
        tags: ["lip-balm", "hydrating", "lipcare", "natural"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "LipLove",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.6,
        reviewsCount: 70,
        hasVariants: true,
        salesCount: 60,
        viewsCount: 1600,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "18",
        name: "লিপ স্ক্রাব",
        slug: "lip-scrub",
        description: "ঠোঁটের মৃত কোষ অপসারণের জন্য প্রাকৃতিক লিপ স্ক্রাব।",
        shortDescription: "ঠোঁটের জন্য লিপ স্ক্রাব",
        sku: "LSC-002",
        price: 400,
        salePrice: 350,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "lc-1",
          name: "লিপ কেয়ার",
          slug: "lipcare",
          description: "ঠোঁটের যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 9,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "lc-1",
        tags: ["lip-scrub", "exfoliating", "lipcare", "natural"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "LipLove",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 60,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
  {
    category: "পার্সোনাল কেয়ার",
    slug: "personal-care",
    banner:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
    products: [
      {
        id: "19",
        name: "বডি ওয়াশ",
        slug: "body-wash",
        description:
          "সতেজ ও হাইড্রেটিং বডি ওয়াশ, সব ধরনের ত্বকের জন্য উপযুক্ত।",
        shortDescription: "সতেজ বডি ওয়াশ",
        sku: "BDW-001",
        price: 500,
        salePrice: 450,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "pc-1",
          name: "পার্সোনাল কেয়ার",
          slug: "personal-care",
          description: "দৈনন্দিন ব্যক্তিগত যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 10,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "pc-1",
        tags: ["body-wash", "hydrating", "personal-care", "daily"],
        stock: 50,
        lowStockThreshold: 10,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "CarePlus",
        status: "published",
        isFeatured: true,
        isDigital: false,
        isActive: true,
        rating: 4.6,
        reviewsCount: 70,
        hasVariants: false,
        salesCount: 60,
        viewsCount: 1600,
        wishlistCount: 25,
        createdAt: new Date("2024-01-10").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
      },
      {
        id: "20",
        name: "হ্যান্ড ক্রিম",
        slug: "hand-cream",
        description: "হাতের ত্বককে নরম ও হাইড্রেটেড রাখার জন্য হ্যান্ড ক্রিম।",
        shortDescription: "হাতের জন্য হ্যান্ড ক্রিম",
        sku: "HDC-002",
        price: 400,
        salePrice: 350,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
        ],
        thumbnail:
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=300&auto=format&fit=crop",
        category: {
          id: "pc-1",
          name: "পার্সোনাল কেয়ার",
          slug: "personal-care",
          description: "দৈনন্দিন ব্যক্তিগত যত্নের পণ্য",
          level: 1,
          isActive: true,
          sort: 10,
          createdAt: new Date("2024-01-01").toISOString(),
          updatedAt: new Date("2024-01-20").toISOString(),
        },
        categoryId: "pc-1",
        tags: ["hand-cream", "hydrating", "personal-care", "daily"],
        stock: 40,
        lowStockThreshold: 8,
        trackStock: true,
        manageStock: true,
        stockStatus: "in-stock",
        brand: "CarePlus",
        status: "published",
        isFeatured: false,
        isDigital: false,
        isActive: true,
        rating: 4.5,
        reviewsCount: 60,
        hasVariants: false,
        salesCount: 50,
        viewsCount: 1500,
        wishlistCount: 20,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
      },
    ],
  },
];

export default CategoriesWiseProduct;
