import { Category } from "@/lip/types/product";

export const categories: Category[] = [
  {
    id: "1",
    name: "স্কিন কেয়ার",
    slug: "skincare",
    description: "Skin care products for all types.",
    image: "https://picsum.photos/seed/skincare/100/100.jpg",
    icon: "https://picsum.photos/seed/skincare/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 1,
    banner: "https://picsum.photos/seed/skincare/100/100.jpg",
    productsCount: "120",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "2",
    name: "মেকআপ",
    slug: "makeup",
    description: "Makeup essentials and accessories.",
    image: "https://picsum.photos/seed/makeup/100/100.jpg",
    icon: "https://picsum.photos/seed/makeup/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 2,
    banner: "https://picsum.photos/seed/makeup/100/100.jpg",
    productsCount: "287",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "3",
    name: "হেয়ার কেয়ার",
    slug: "hair-care",
    description: "Hair care products for styling and nourishment.",
    image: "https://picsum.photos/seed/haircare/100/100.jpg",
    icon: "https://picsum.photos/seed/haircare/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 3,
    banner: "https://picsum.photos/seed/haircare/100/100.jpg",
    productsCount: "198",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "4",
    name: "ফ্র্যাগরেন্স",
    slug: "fragrance",
    description: "Perfumes and body mists.",
    image: "https://picsum.photos/seed/fragrance/100/100.jpg",
    icon: "https://picsum.photos/seed/fragrance/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 4,
    banner: "https://picsum.photos/seed/fragrance/100/100.jpg",
    productsCount: "156",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "5",
    name: "বাথ অ্যান্ড বডি",
    slug: "bath-body",
    description: "Bath and body care essentials.",
    image: "https://picsum.photos/seed/bathbody/100/100.jpg",
    icon: "https://picsum.photos/seed/bathbody/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 5,
    banner: "https://picsum.photos/seed/bathbody/100/100.jpg",
    productsCount: "203",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "6",
    name: "নেইল কেয়ার",
    slug: "nail-care",
    description: "Nail polish and manicure tools.",
    image: "https://picsum.photos/seed/nailcare/100/100.jpg",
    icon: "https://picsum.photos/seed/nailcare/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 6,
    banner: "https://picsum.photos/seed/nailcare/100/100.jpg",
    productsCount: "124",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "7",
    name: "মেন'স গ্রুমিং",
    slug: "mens-grooming",
    description: "Men's grooming products.",
    image: "https://picsum.photos/seed/mensgrooming/100/100.jpg",
    icon: "https://picsum.photos/seed/mensgrooming/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 7,
    banner: "https://picsum.photos/seed/mensgrooming/100/100.jpg",
    productsCount: "178",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "8",
    name: "অর্গানিক বিউটি",
    slug: "organic-beauty",
    description: "Organic and natural beauty products.",
    image: "https://picsum.photos/seed/organicbeauty/100/100.jpg",
    icon: "https://picsum.photos/seed/organicbeauty/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 8,
    banner: "https://picsum.photos/seed/organicbeauty/100/100.jpg",
    productsCount: "95",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "9",
    name: "লাক্সারি বিউটি",
    slug: "luxury-beauty",
    description: "Premium and luxury beauty items.",
    image: "https://picsum.photos/seed/luxurybeauty/100/100.jpg",
    icon: "https://picsum.photos/seed/luxurybeauty/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 9,
    banner: "https://picsum.photos/seed/luxurybeauty/100/100.jpg",
    productsCount: "67",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "10",
    name: "সান কেয়ার",
    slug: "sun-care",
    description: "Sun protection and after-sun care.",
    image: "https://picsum.photos/seed/suncare/100/100.jpg",
    icon: "https://picsum.photos/seed/suncare/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 10,
    banner: "https://picsum.photos/seed/suncare/100/100.jpg",
    productsCount: "142",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "11",
    name: "বিউটি টুলস",
    slug: "beauty-tools",
    description: "Tools and accessories for beauty routines.",
    image: "https://picsum.photos/seed/beautytools/100/100.jpg",
    icon: "https://picsum.photos/seed/beautytools/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 11,
    banner: "https://picsum.photos/seed/beautytools/100/100.jpg",
    productsCount: "89",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "12",
    name: "ওয়েলনেস অ্যান্ড স্পা",
    slug: "wellness-spa",
    description: "Wellness and spa products.",
    image: "https://picsum.photos/seed/wellnessspa/100/100.jpg",
    icon: "https://picsum.photos/seed/wellnessspa/100/100.jpg",
    level: 1,
    isActive: true,
    sort: 12,
    banner: "https://picsum.photos/seed/wellnessspa/100/100.jpg",
    productsCount: "176",
    createdAt: "",
    updatedAt: "",
  },
];
