import { Product } from "@/lip/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "গ্লো রেডিয়েন্স ভিটামিন সি সেরাম",
    slug: "glow-radiance-vitamin-c-serum",
    description:
      "উন্নত ভিটামিন সি ফর্মুলা যা ত্বককে উজ্জ্বল করে এবং বয়সের ছাপ কমায়। প্রাকৃতিক উপাদান দিয়ে তৈরি।",
    shortDescription: "ভিটামিন সি সেরাম - ত্বকের উজ্জ্বলতার জন্য",
    sku: "GRC-001",
    price: 1200,
    salePrice: 950,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      description: "ত্বকের যত্নের পণ্য",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["serum", "vitamin-c", "anti-aging", "brightening"],
    stock: 50,
    lowStockThreshold: 10,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "GlowCare",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 124,
    hasVariants: false,
    salesCount: 89,
    viewsCount: 2156,
    wishlistCount: 45,
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "2",
    name: "হায়ালুরনিক এসিড মশ্চারাইজার",
    slug: "hyaluronic-acid-moisturizer",
    description:
      "গভীর আর্দ্রতা প্রদান করে এবং ত্বকের স্থিতিস্থাপকতা বৃদ্ধি করে। সব ধরনের ত্বকের জন্য উপযুক্ত।",
    shortDescription: "হায়ালুরনিক এসিড মশ্চারাইজার - গভীর আর্দ্রতার জন্য",
    sku: "HAM-002",
    price: 1500,
    salePrice: 1200,
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0b?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["moisturizer", "hyaluronic-acid", "hydrating"],
    stock: 30,
    lowStockThreshold: 10,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "AquaGlow",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 98,
    hasVariants: false,
    salesCount: 67,
    viewsCount: 1890,
    wishlistCount: 32,
    createdAt: new Date("2024-01-02").toISOString(),
    updatedAt: new Date("2024-01-16").toISOString(),
  },
  {
    id: "3",
    name: "ম্যাট ফিনিশ এলো ভেরা জেল",
    slug: "matte-finish-aloe-vera-gel",
    description:
      "প্রাকৃতিক এলো ভেরার গুণাগুণ সহ ম্যাট ফিনিশ জেল। ত্বকের প্রদাহ কমায় এবং শান্ত করে।",
    shortDescription: "এলো ভেরা জেল - প্রাকৃতিক ত্বকের যত্নে",
    sku: "AVG-003",
    price: 800,
    images: [
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["aloe-vera", "gel", "soothing", "natural"],
    stock: 75,
    lowStockThreshold: 15,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "PureCare",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.4,
    reviewsCount: 156,
    hasVariants: false,
    salesCount: 123,
    viewsCount: 1456,
    wishlistCount: 28,
    createdAt: new Date("2024-01-03").toISOString(),
    updatedAt: new Date("2024-01-17").toISOString(),
  },
  {
    id: "4",
    name: "রোজ গোল্ড হাইলাইটার প্যালেট",
    slug: "rose-gold-highlighter-palette",
    description:
      "চারটি আলাদা শেডের হাইলাইটার প্যালেট। মুখের প্রাকৃতিক আভা বাড়ায় এবং দীর্ঘস্থায়ী।",
    shortDescription: "রোজ গোল্ড হাইলাইটার - প্রাকৃতিক আভার জন্য",
    sku: "RGH-004",
    price: 2200,
    salePrice: 1800,
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "mk-1",
      name: "মেকআপ",
      slug: "makeup",
      description: "সৌন্দর্য বর্ধনকারী মেকআপ পণ্য",
      level: 1,
      isActive: true,
      sort: 2,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "mk-1",
    tags: ["highlighter", "makeup", "rose-gold", "glow"],
    stock: 25,
    lowStockThreshold: 5,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "GlowUp",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.7,
    reviewsCount: 87,
    hasVariants: false,
    salesCount: 54,
    viewsCount: 1789,
    wishlistCount: 41,
    createdAt: new Date("2024-01-04").toISOString(),
    updatedAt: new Date("2024-01-18").toISOString(),
  },
  {
    id: "5",
    name: "অর্গানিক গ্রিন টি ফেস মাস্ক",
    slug: "organic-green-tea-face-mask",
    description:
      "প্রাকৃতিক গ্রিন টি এবং ক্লে দিয়ে তৈরি। ত্বকের গভীর থেকে পরিষ্কার করে এবং পুষ্টি প্রদান করে।",
    shortDescription: "গ্রিন টি ফেস মাস্ক - প্রাকৃতিক ডিটক্স",
    sku: "GTM-005",
    price: 900,
    images: [
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["face-mask", "green-tea", "organic", "detox"],
    stock: 40,
    lowStockThreshold: 10,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "NaturaCare",
    status: "published",
    isFeatured: false,
    isDigital: false,
    isActive: true,
    rating: 4.3,
    reviewsCount: 112,
    hasVariants: false,
    salesCount: 78,
    viewsCount: 1234,
    wishlistCount: 19,
    createdAt: new Date("2024-01-05").toISOString(),
    updatedAt: new Date("2024-01-19").toISOString(),
  },
  {
    id: "6",
    name: "লং লাস্টিং ম্যাট লিপস্টিক সেট",
    slug: "long-lasting-matte-lipstick-set",
    description:
      "৬টি জনপ্রিয় শেডের ম্যাট লিপস্টিক সেট। ১২ ঘন্টা পর্যন্ত টেকসই এবং ত্বক-বান্ধব।",
    shortDescription: "ম্যাট লিপস্টিক সেট - দীর্ঘস্থায়ী সৌন্দর্য",
    sku: "MLS-006",
    price: 3500,
    salePrice: 2800,
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "mk-1",
      name: "মেকআপ",
      slug: "makeup",
      level: 1,
      isActive: true,
      sort: 2,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "mk-1",
    tags: ["lipstick", "matte", "long-lasting", "set"],
    stock: 20,
    lowStockThreshold: 5,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "ColorPop",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.9,
    reviewsCount: 203,
    hasVariants: true,
    salesCount: 145,
    viewsCount: 3456,
    wishlistCount: 89,
    createdAt: new Date("2024-01-06").toISOString(),
    updatedAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: "7",
    name: "নাচারাল হেয়ার গ্রোথ অয়েল",
    slug: "natural-hair-growth-oil",
    description:
      "আয়ুর্বেদিক তেল যা চুলের বৃদ্ধি ত্বরান্বিত করে। নারিকেল, অলিভ এবং ক্যাস্টর অয়েলের মিশ্রণ।",
    shortDescription: "হেয়ার গ্রোথ অয়েল - প্রাকৃতিক চুলের যত্ন",
    sku: "HGO-007",
    price: 1100,
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "hc-1",
      name: "হেয়ারকেয়ার",
      slug: "haircare",
      description: "চুলের যত্নের পণ্য",
      level: 1,
      isActive: true,
      sort: 3,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "hc-1",
    tags: ["hair-oil", "growth", "natural", "ayurvedic"],
    stock: 60,
    lowStockThreshold: 15,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "HerbalCare",
    status: "published",
    isFeatured: false,
    isDigital: false,
    isActive: true,
    rating: 4.5,
    reviewsCount: 167,
    hasVariants: false,
    salesCount: 98,
    viewsCount: 1567,
    wishlistCount: 34,
    createdAt: new Date("2024-01-07").toISOString(),
    updatedAt: new Date("2024-01-21").toISOString(),
  },
  {
    id: "8",
    name: "সানস্ক্রিন এসপিএফ ৫০+",
    slug: "sunscreen-spf-50-plus",
    description:
      "উন্নত ইউভি প্রতিরক্ষা সহ সানস্ক্রিন। জল প্রতিরোধী এবং সব ধরনের ত্বকের জন্য নিরাপদ।",
    shortDescription: "সানস্ক্রিন SPF 50+ - সূর্যের ক্ষতি থেকে সুরক্ষা",
    sku: "SS50-008",
    price: 1300,
    salePrice: 1050,
    images: [
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0b?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["sunscreen", "spf50", "uv-protection", "water-resistant"],
    stock: 35,
    lowStockThreshold: 8,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "SunGuard",
    status: "published",
    isFeatured: false,
    isDigital: false,
    isActive: true,
    rating: 4.6,
    reviewsCount: 134,
    hasVariants: false,
    salesCount: 76,
    viewsCount: 1890,
    wishlistCount: 42,
    createdAt: new Date("2024-01-08").toISOString(),
    updatedAt: new Date("2024-01-22").toISOString(),
  },
  {
    id: "9",
    name: "নিম এন্ড তুলসী ফেস ওয়াশ",
    slug: "neem-tulsi-face-wash",
    description:
      "নিম এবং তুলসীর প্রাকৃতিক গুণাগুণ সহ ফেস ওয়াশ। ব্রণ প্রতিরোধ করে এবং ত্বক পরিষ্কার রাখে।",
    shortDescription: "নিম তুলসী ফেস ওয়াশ - প্রাকৃতিক পরিষ্কারতা",
    sku: "NTF-009",
    price: 650,
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["face-wash", "neem", "tulsi", "acne-control"],
    stock: 80,
    lowStockThreshold: 20,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "AyurVeda",
    status: "published",
    isFeatured: false,
    isDigital: false,
    isActive: true,
    rating: 4.2,
    reviewsCount: 189,
    hasVariants: false,
    salesCount: 156,
    viewsCount: 1123,
    wishlistCount: 25,
    createdAt: new Date("2024-01-09").toISOString(),
    updatedAt: new Date("2024-01-23").toISOString(),
  },
  {
    id: "10",
    name: "ভলিউমাইজিং মাস্কারা",
    slug: "volumizing-mascara",
    description:
      "চোখের পাপড়িকে ঘন এবং লম্বা দেখায়। জলরোধী এবং সারাদিন টেকসই।",
    shortDescription: "ভলিউমাইজিং মাস্কারা - আকর্ষণীয় চোখের জন্য",
    sku: "VM-010",
    price: 1800,
    salePrice: 1440,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "mk-1",
      name: "মেকআপ",
      slug: "makeup",
      level: 1,
      isActive: true,
      sort: 2,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "mk-1",
    tags: ["mascara", "volumizing", "waterproof", "long-lasting"],
    stock: 45,
    lowStockThreshold: 10,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "EyeGlow",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.7,
    reviewsCount: 145,
    hasVariants: false,
    salesCount: 89,
    viewsCount: 2345,
    wishlistCount: 67,
    createdAt: new Date("2024-01-10").toISOString(),
    updatedAt: new Date("2024-01-24").toISOString(),
  },
  {
    id: "11",
    name: "কোকোনাট অয়েল হেয়ার মাস্ক",
    slug: "coconut-oil-hair-mask",
    description:
      "গভীর পুষ্টি প্রদানকারী হেয়ার মাস্ক। শুষ্ক এবং ক্ষতিগ্রস্ত চুল মেরামত করে।",
    shortDescription: "কোকোনাট হেয়ার মাস্ক - গভীর পুষ্টির জন্য",
    sku: "CHM-011",
    price: 950,
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "hc-1",
      name: "হেয়ারকেয়ার",
      slug: "haircare",
      level: 1,
      isActive: true,
      sort: 3,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "hc-1",
    tags: ["hair-mask", "coconut-oil", "deep-conditioning", "repair"],
    stock: 55,
    lowStockThreshold: 12,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "TropicalCare",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.4,
    reviewsCount: 123,
    hasVariants: false,
    salesCount: 67,
    viewsCount: 1456,
    wishlistCount: 29,
    createdAt: new Date("2024-01-11").toISOString(),
    updatedAt: new Date("2024-01-25").toISOString(),
  },
  {
    id: "12",
    name: "রেটিনল নাইট ক্রিম",
    slug: "retinol-night-cream",
    description:
      "শক্তিশালী রেটিনল ফর্মুলা যা রাতের বেলায় ত্বক পুনর্গঠন করে। বয়সের ছাপ কমায়।",
    shortDescription: "রেটিনল নাইট ক্রিম - রাতের পুনর্গঠন",
    sku: "RNC-012",
    price: 2500,
    salePrice: 2000,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0b?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "sk-1",
      name: "স্কিনকেয়ার",
      slug: "skincare",
      level: 1,
      isActive: true,
      sort: 1,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "sk-1",
    tags: ["retinol", "night-cream", "anti-aging", "renewal"],
    stock: 15,
    lowStockThreshold: 5,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "AgelessBeauty",
    status: "published",
    isFeatured: true,
    isDigital: false,
    isActive: true,
    rating: 4.8,
    reviewsCount: 78,
    hasVariants: false,
    salesCount: 45,
    viewsCount: 1789,
    wishlistCount: 56,
    createdAt: new Date("2024-01-12").toISOString(),
    updatedAt: new Date("2024-01-26").toISOString(),
  },
  {
    id: "13",
    name: "ন্যাচারাল ব্লাশ পালেট",
    slug: "natural-blush-palette",
    description:
      "চারটি প্রাকৃতিক শেডের ব্লাশ পালেট। হালকা থেকে গাঢ় সব রঙের জন্য উপযুক্ত।",
    shortDescription: "ন্যাচারাল ব্লাশ পালেট - প্রাকৃতিক রঙ পালেট",
    sku: "NBP-013",
    price: 800,
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1000&auto=format&fit=crop",
    ],
    thumbnail:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=300&auto=format&fit=crop",
    category: {
      id: "mk-1",
      name: "মেকআপ",
      slug: "makeup",
      level: 1,
      isActive: true,
      sort: 2,
      createdAt: new Date("2024-01-01").toISOString(),
      updatedAt: new Date("2024-01-15").toISOString(),
    },
    categoryId: "mk-1",
    tags: ["blush", "natural", "palette", "set"],
    stock: 30,
    lowStockThreshold: 8,
    trackStock: true,
    manageStock: true,
    stockStatus: "in-stock",
    brand: "PureNature",
    status: "published",
    isFeatured: false,
    isDigital: false,
    isActive: true,
    rating: 4.3,
    reviewsCount: 102,
    hasVariants: false,
    salesCount: 34,
    viewsCount: 1234,
    wishlistCount: 23,
    createdAt: new Date("2024-01-13").toISOString(),
    updatedAt: new Date("2024-01-27").toISOString(),
  },
];
