import { Brand } from "@/lip/types/brand";

export const brands: Brand[] = [
  {
    id: "1",
    name: "L'Oreal Paris",
    logo: "https://picsum.photos/seed/loreal/200/80.jpg",
    slug: "loreal-paris",
    productCount: 342,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },

  {
    id: "2",
    name: "Estée Lauder",
    logo: "https://picsum.photos/seed/estee-laude/200/80.jpg",
    slug: "estee-lauder",
    productCount: 287,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "3",
    name: "MAC Cosmetics",
    logo: "https://picsum.photos/seed/mac-cosmetics/200/80.jpg",
    slug: "mac-cosmetics",
    productCount: 198,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "4",
    name: "Maybelline New York",
    logo: "https://picsum.photos/seed/maybelline/200/80.jpg",
    slug: "maybelline-new-york",
    productCount: 256,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "5",
    name: "Clinique",
    logo: "https://picsum.photos/seed/clinique/200/80.jpg",
    slug: "clinique",
    productCount: 187,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "6",
    name: "Lancôme",
    logo: "https://picsum.photos/seed/lancome/200/80.jpg",
    slug: "lancome",
    productCount: 156,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "7",
    name: "Olay",
    logo: "https://picsum.photos/seed/olay/200/80.jpg",
    slug: "olay",
    productCount: 134,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "8",
    name: "Neutrogena",
    logo: "https://picsum.photos/seed/neutrogena/200/80.jpg",
    slug: "neutrogena",
    productCount: 178,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "9",
    name: "Garnier",
    logo: "https://picsum.photos/seed/garnier/200/80.jpg",
    slug: "garnier",
    productCount: 223,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "10",
    name: "Nivea",
    logo: "https://picsum.photos/seed/nivea/200/80.jpg",
    slug: "nivea",
    productCount: 298,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "11",
    name: "Dove",
    logo: "https://picsum.photos/seed/dove/200/80.jpg",
    slug: "dove",
    productCount: 267,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
  {
    id: "12",
    name: "Pantene",
    logo: "https://picsum.photos/seed/pantene/200/80.jpg",
    slug: "pantene",
    productCount: 145,
    seo: {
      metaTitle: "Pantene Skin Care",
      metaDescription: "Discover the best products for your skin",
      keywords: ["pantene", "skin care", "beauty"],
      canonical: "https://www.sundoritto.com/pantene-skin-care",
    },
  },
];
